export interface Image {
	filename: string;
	id: string;
}

export interface Link {
  url: string
}

export interface LandingContent {
	title: string;
	lead?: string;
}

export interface Project {
  title: string;
  description: string;
  image: Image;
  link: Link;
}

export interface Article {
	title: string;
	description: string;
	image: Image;
	link: Link;
}

export interface Landing {
	content: LandingContent;
}

export interface Projects {
	content: Project[];
}

export interface Articles {
	content: Article[];
}

export interface Stories {
	landing: Landing;
  projects: Projects;
  articles: Articles;
}

export interface LandingData {
	stories: Stories;
}

// And then for your PageProps if it's not already defined like this
// If PageProps is generated by SvelteKit, you might need to adjust based on its exact structure.
// For example, if SvelteKit's PageProps has a 'data' property
export interface PageProps {
  data: {
    landingData: LandingData;
  };
}
